source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "just-the-docs", "0.3.3"
gem "liquid", ">= 4.0.4"   # 4.0.3 uses tainted? removed in Ruby 3.2
gem "webrick"

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
  gem "wdm", "~> 0.1.1"
end
