name: aarch64 Wheels

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  build_wheels:
    name: Build aarch64 wheels
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3
      name: Set up QEMU (emulator for aarch64)

    - name: Prepare source files
      # Using shell: bash keeps this in sync with wheels.yml
      shell: bash
      run: |
        mkdir -p interfaces/daqp-python/csrc
        cp -r src interfaces/daqp-python/csrc/src
        cp -r include interfaces/daqp-python/csrc/include
        cp -r codegen interfaces/daqp-python/csrc/codegen
        cp CMakeLists.txt interfaces/daqp-python/csrc/CMakeLists.txt
        cp LICENSE interfaces/daqp-python/LICENSE

    - name: Build wheels
      uses: pypa/cibuildwheel@v3.4.0
      env:
        CIBW_ARCHS_LINUX: aarch64
        CIBW_SKIP: "pp*"
      with:
        package-dir: interfaces/daqp-python
        output-dir: interfaces/daqp-python/wheelhouse

    - name: Release to pypi
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN}}
      run: |
        cd interfaces/daqp-python
        pipx run twine upload wheelhouse/* --skip-existing

    - name: Upload artifacts to github
      uses: actions/upload-artifact@v4
      with:
        name: wheels-aarch64
        path: interfaces/daqp-python/wheelhouse/*
