name: Python Wheels

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    tags: ['v*']

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2022]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: '3.11'

    - name: Prepare source files
      # Using shell: bash ensures consistency across Windows and Linux runners
      shell: bash
      run: |
        mkdir -p interfaces/daqp-python/csrc
        cp -r src interfaces/daqp-python/csrc/src
        cp -r include interfaces/daqp-python/csrc/include
        cp -r codegen interfaces/daqp-python/csrc/codegen
        cp CMakeLists.txt interfaces/daqp-python/csrc/CMakeLists.txt
        cp LICENSE interfaces/daqp-python/LICENSE

    - name: Build wheels
      uses: pypa/cibuildwheel@v3.4.0
      env:
        CIBW_SKIP: "pp* *-musllinux*"
        CIBW_ARCHS_MACOS: "x86_64 arm64"
        CIBW_TEST_REQUIRES: "pytest numpy"
        CIBW_TEST_COMMAND: "pytest -s {package}/test"
      with:
        package-dir: interfaces/daqp-python
        output-dir: interfaces/daqp-python/wheelhouse

    - name: Build source
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        cd interfaces/daqp-python
        pipx run build --sdist --outdir wheelhouse

    - name: Release to pypi
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN}}
      run: |
        cd interfaces/daqp-python
        pipx run twine upload wheelhouse/* --skip-existing

    - name: Upload artifacts to github
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: interfaces/daqp-python/wheelhouse/*
